# Tell Travis you want a Python environment to test in
sudo: false
language: python

# List the versions of Python you'd like to test against
python:
  - "2.7"

# List the versions of Django you'd like to test against
env:
  - DJANGO="Django>=1.8"

install:
   # Install the dependencies the app itself has
   # which in this case I choose to keep in a requirements file
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install -q $DJANGO
# Tell Travis how to run the test script itself
script:
  - coverage run --source=feeds test.py -m py.test
after_success:
  - coveralls
